# Нужна установленная kanshi - для автонастройки мониторов по конфигу
exec kanshi

# Переместить рабочее пространство на монитор справа
# Строки ниже вроде есть в основном конфиге
# bindsym $mod+Shift+Right move workspace to output right
# bindsym $mod+Shift+Left move workspace to output left

# Привязать рабочие области к конкретным мониторам
# Мониторы через swaymsg -t get_outputs
workspace 0 output eDP-1
workspace 3 output HDMI-A-1

