exec swaymsg "workspace 1; exec flatpak run org.telegram.desktop"
exec swaymsg "workspace 2; exec foot"
exec swaymsg "workspace 8; exec flatpak run md.obsidian.Obsidian"
exec sleep 5 && swaymsg "workspace 10; exec google-chrome; exec flatpak run org.gajim.Gajim"
# exec swaymsg "workspace 10; exec flatpak run org.gajim.Gajim"
